### ISSUE TITLE
v3.2.1 RimeData preedit_comment正则错误

### ISSUE THREAD

**Issue by WindyValley** [Jackchows/Cangjie5#288]
20240518的Release里，默认preedit_comment中的正则错误，查看buildRelease.py脚本发现已经修正，是否可以重新发布release？
![image](https://github.com/Jackchows/Cangjie5/assets/48832872/f3dac0f1-3c98-4982-ad42-651a3b48a0f1)

**Comment by WindyValley** [comment]
看起来现在方案里的正则是为了处理
zsxxx=㇣
这种后面有多个x的，我再研究一下

**Comment by WindyValley** [comment]
``` yaml
  translator/preedit_format:  # 已輸入編碼
    - 'xform/^([a-z]*)$/$1\t（\U$1\E）/'
    - 'xform/(?<=（)X/#/'
    - 'xform/(?<=（X)X/#/'
    - 'xform/(?<=（XX)X/#/'
    - 'xform/(?<=（XXX)X/#/'
    - 'xform/(?<=（XXXX)X/#/'
    - "xlit|ABCDEFGHIJKLMNOPQRSTUVWXYZ#|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符重|"
  translator/comment_format:  # 編碼提示
    - 'xform/(?<=^)x/#/'
    - 'xform/(?<=^x)x/#/'
    - 'xform/(?<=^xx)x/#/'
    - 'xform/(?<=^xxx)x/#/'
    - 'xform/(?<=^xxxx)x/#/'
    - "xlit|abcdefghijklmnopqrstuvwxyz#~|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符重～|"
  reverse_lookup:
    dictionary: rime_ice
    prism: double_pinyin_flypy
    prefix: "`"
    suffix: "'"
    tips: 〔双拼〕
    overwrite_comment: true
    comment_format:
      - "xform/$/〕/"
      - "xform/^/〔/"
      - 'xform/(?<=^)x/#/'
      - 'xform/(?<=^x)x/#/'
      - 'xform/(?<=^xx)x/#/'
      - 'xform/(?<=^xxx)x/#/'
      - 'xform/(?<=^xxxx)x/#/'
      - "xlit|abcdefghijklmnopqrstuvwxyz#~ |日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符重～、|"
```

librime使用的boost_regex里的perl正则似乎不支持在反向查找表达式里使用通配符，只能这样枚举了，左右最多也就五个码🤣
